name: pages

on:

  push:
    branches: ["pages"]

  workflow_dispatch:

permissions:

  contents: read
  pages: write
  id-token: write

concurrency:

  group: "pages"
  cancel-in-progress: true

jobs:

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: "pages"

      - name: configure
        uses: actions/configure-pages@v2

      - name: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v1
